import {
  type LucideIcon,
  LayoutDashboard,
  BarChart3,
  FlaskConical,
  Briefcase,
  Database,
  Brain,
  Settings,
  Shield,
  LineChart,
  Target,
  Zap,
  PieChart,
  TrendingUp,
  Activity,
  Users,
  Key,
  Bell,
  Lock,
  CreditCard,
  Palette,
  Server,
  ScrollText,
} from 'lucide-react';

export interface RouteConfig {
  path: string;
  label: string;
  labelEn: string;
  icon?: LucideIcon;
  parent?: string;
  requiredRole?: 'user' | 'analyst' | 'admin';
  requiresAuth: boolean;
  showInSidebar: boolean;
  sidebarGroup?: string;
  badge?: 'beta' | 'new' | 'pro';
  shortcut?: string;
  meta: {
    title: string;
    description: string;
    noIndex?: boolean;
  };
}

export const ROUTES: Record<string, RouteConfig> = {
  dashboard: {
    path: '/dashboard',
    label: 'nav.dashboard',
    labelEn: 'Dashboard',
    icon: LayoutDashboard,
    requiresAuth: true,
    requiredRole: 'user',
    showInSidebar: true,
    sidebarGroup: 'main',
    shortcut: 'g d',
    meta: { title: 'Dashboard — Pyhron', description: 'Portfolio overview and command center' },
  },
  dashboardOverview: {
    path: '/dashboard/overview',
    label: 'nav.dashboard',
    labelEn: 'Overview',
    parent: '/dashboard',
    requiresAuth: true,
    showInSidebar: false,
    meta: { title: 'Portfolio Overview — Pyhron', description: 'Detailed portfolio overview' },
  },
  markets: {
    path: '/markets',
    label: 'nav.markets',
    labelEn: 'Markets',
    icon: BarChart3,
    requiresAuth: true,
    requiredRole: 'user',
    showInSidebar: true,
    sidebarGroup: 'main',
    shortcut: 'g m',
    meta: { title: 'Markets — Pyhron', description: 'IDX market overview and instrument data' },
  },
  marketsScreener: {
    path: '/markets/screener',
    label: 'markets.screener',
    labelEn: 'Screener',
    icon: Target,
    parent: '/markets',
    requiresAuth: true,
    showInSidebar: true,
    sidebarGroup: 'markets',
    meta: { title: 'Stock Screener — Pyhron', description: 'Multi-factor stock screening' },
  },
  marketsWatchlists: {
    path: '/markets/watchlists',
    label: 'markets.watchlists',
    labelEn: 'Watchlists',
    parent: '/markets',
    requiresAuth: true,
    showInSidebar: true,
    sidebarGroup: 'markets',
    meta: { title: 'Watchlists — Pyhron', description: 'Manage watchlists' },
  },
  marketsCalendar: {
    path: '/markets/calendar',
    label: 'markets.calendar',
    labelEn: 'Calendar',
    parent: '/markets',
    requiresAuth: true,
    showInSidebar: true,
    sidebarGroup: 'markets',
    meta: { title: 'Calendar — Pyhron', description: 'Economic and earnings calendar' },
  },
  research: {
    path: '/research/dashboard',
    label: 'nav.research',
    labelEn: 'Research',
    icon: FlaskConical,
    requiresAuth: true,
    requiredRole: 'user',
    showInSidebar: true,
    sidebarGroup: 'main',
    shortcut: 'g r',
    meta: { title: 'Research — Pyhron', description: 'Quantitative research hub' },
  },
  researchSignals: {
    path: '/research/signals',
    label: 'research.signals',
    labelEn: 'Signals',
    icon: Zap,
    parent: '/research/dashboard',
    requiresAuth: true,
    showInSidebar: true,
    sidebarGroup: 'research',
    meta: { title: 'Signals — Pyhron', description: 'ML-generated trading signals' },
  },
  researchBacktests: {
    path: '/research/backtests',
    label: 'research.backtests',
    labelEn: 'Backtests',
    icon: LineChart,
    parent: '/research/dashboard',
    requiresAuth: true,
    showInSidebar: true,
    sidebarGroup: 'research',
    meta: { title: 'Backtests — Pyhron', description: 'Backtest results browser' },
  },
  researchFactors: {
    path: '/research/factors',
    label: 'research.factors',
    labelEn: 'Factors',
    icon: PieChart,
    parent: '/research/dashboard',
    requiresAuth: true,
    showInSidebar: true,
    sidebarGroup: 'research',
    badge: 'pro',
    meta: { title: 'Factor Analysis — Pyhron', description: 'Factor analysis dashboard' },
  },
  strategies: {
    path: '/strategies',
    label: 'nav.strategies',
    labelEn: 'Strategies',
    icon: Briefcase,
    requiresAuth: true,
    requiredRole: 'user',
    showInSidebar: true,
    sidebarGroup: 'main',
    shortcut: 'g s',
    meta: { title: 'Strategies — Pyhron', description: 'Strategy management console' },
  },
  strategyBuilder: {
    path: '/strategies/builder',
    label: 'strategies.builder',
    labelEn: 'Builder',
    parent: '/strategies',
    requiresAuth: true,
    showInSidebar: true,
    sidebarGroup: 'strategies',
    badge: 'beta',
    meta: { title: 'Strategy Builder — Pyhron', description: 'Visual strategy builder' },
  },
  portfolio: {
    path: '/portfolio',
    label: 'nav.portfolio',
    labelEn: 'Portfolio',
    icon: TrendingUp,
    requiresAuth: true,
    requiredRole: 'user',
    showInSidebar: true,
    sidebarGroup: 'main',
    shortcut: 'g p',
    meta: { title: 'Portfolio — Pyhron', description: 'Portfolio management' },
  },
  portfolioPositions: {
    path: '/portfolio/positions',
    label: 'portfolio.positions',
    labelEn: 'Positions',
    parent: '/portfolio',
    requiresAuth: true,
    showInSidebar: true,
    sidebarGroup: 'portfolio',
    meta: { title: 'Positions — Pyhron', description: 'Current positions with real-time P&L' },
  },
  portfolioOrders: {
    path: '/portfolio/orders',
    label: 'portfolio.orders',
    labelEn: 'Orders',
    parent: '/portfolio',
    requiresAuth: true,
    showInSidebar: true,
    sidebarGroup: 'portfolio',
    meta: { title: 'Orders — Pyhron', description: 'Order management' },
  },
  portfolioRisk: {
    path: '/portfolio/risk',
    label: 'portfolio.risk',
    labelEn: 'Risk',
    icon: Shield,
    parent: '/portfolio',
    requiresAuth: true,
    showInSidebar: true,
    sidebarGroup: 'portfolio',
    shortcut: 'g k',
    meta: { title: 'Risk Dashboard — Pyhron', description: 'Risk analytics dashboard' },
  },
  portfolioPerformance: {
    path: '/portfolio/performance',
    label: 'portfolio.performance',
    labelEn: 'Performance',
    parent: '/portfolio',
    requiresAuth: true,
    showInSidebar: true,
    sidebarGroup: 'portfolio',
    meta: { title: 'Performance — Pyhron', description: 'Performance attribution' },
  },
  portfolioHistory: {
    path: '/portfolio/history',
    label: 'portfolio.history',
    labelEn: 'History',
    parent: '/portfolio',
    requiresAuth: true,
    showInSidebar: true,
    sidebarGroup: 'portfolio',
    meta: { title: 'Trade History — Pyhron', description: 'Trade history' },
  },
  execution: {
    path: '/execution',
    label: 'nav.execution',
    labelEn: 'Execution',
    icon: Activity,
    requiresAuth: true,
    requiredRole: 'analyst',
    showInSidebar: true,
    sidebarGroup: 'advanced',
    badge: 'pro',
    meta: { title: 'Execution — Pyhron', description: 'Execution management' },
  },
  data: {
    path: '/data',
    label: 'nav.data',
    labelEn: 'Data',
    icon: Database,
    requiresAuth: true,
    requiredRole: 'analyst',
    showInSidebar: true,
    sidebarGroup: 'advanced',
    meta: { title: 'Data — Pyhron', description: 'Data management' },
  },
  ml: {
    path: '/ml',
    label: 'nav.ml',
    labelEn: 'ML Pipeline',
    icon: Brain,
    requiresAuth: true,
    requiredRole: 'analyst',
    showInSidebar: true,
    sidebarGroup: 'advanced',
    badge: 'pro',
    meta: { title: 'ML Pipeline — Pyhron', description: 'Machine learning pipeline' },
  },
  settings: {
    path: '/settings',
    label: 'nav.settings',
    labelEn: 'Settings',
    icon: Settings,
    requiresAuth: true,
    showInSidebar: true,
    sidebarGroup: 'system',
    shortcut: 'g ,',
    meta: { title: 'Settings — Pyhron', description: 'User settings', noIndex: true },
  },
  settingsProfile: {
    path: '/settings/profile',
    label: 'settings.profile',
    labelEn: 'Profile',
    icon: Users,
    parent: '/settings',
    requiresAuth: true,
    showInSidebar: false,
    meta: { title: 'Profile — Pyhron', description: 'Profile management', noIndex: true },
  },
  settingsApiKeys: {
    path: '/settings/api-keys',
    label: 'settings.apiKeys',
    labelEn: 'API Keys',
    icon: Key,
    parent: '/settings',
    requiresAuth: true,
    showInSidebar: false,
    meta: { title: 'API Keys — Pyhron', description: 'API key management', noIndex: true },
  },
  settingsNotifications: {
    path: '/settings/notifications',
    label: 'settings.notifications',
    labelEn: 'Notifications',
    icon: Bell,
    parent: '/settings',
    requiresAuth: true,
    showInSidebar: false,
    meta: { title: 'Notifications — Pyhron', description: 'Notification preferences', noIndex: true },
  },
  settingsSecurity: {
    path: '/settings/security',
    label: 'settings.security',
    labelEn: 'Security',
    icon: Lock,
    parent: '/settings',
    requiresAuth: true,
    showInSidebar: false,
    meta: { title: 'Security — Pyhron', description: 'Security settings', noIndex: true },
  },
  settingsBilling: {
    path: '/settings/billing',
    label: 'settings.billing',
    labelEn: 'Billing',
    icon: CreditCard,
    parent: '/settings',
    requiresAuth: true,
    showInSidebar: false,
    meta: { title: 'Billing — Pyhron', description: 'Subscription and billing', noIndex: true },
  },
  settingsAppearance: {
    path: '/settings/appearance',
    label: 'settings.appearance',
    labelEn: 'Appearance',
    icon: Palette,
    parent: '/settings',
    requiresAuth: true,
    showInSidebar: false,
    meta: { title: 'Appearance — Pyhron', description: 'Theme and display preferences', noIndex: true },
  },
  admin: {
    path: '/admin',
    label: 'nav.admin',
    labelEn: 'Admin',
    icon: Shield,
    requiresAuth: true,
    requiredRole: 'admin',
    showInSidebar: true,
    sidebarGroup: 'system',
    meta: { title: 'Admin — Pyhron', description: 'Admin panel', noIndex: true },
  },
  adminUsers: {
    path: '/admin/users',
    label: 'admin.users',
    labelEn: 'Users',
    icon: Users,
    parent: '/admin',
    requiresAuth: true,
    requiredRole: 'admin',
    showInSidebar: false,
    meta: { title: 'User Management — Pyhron', description: 'Manage users', noIndex: true },
  },
  adminSystem: {
    path: '/admin/system',
    label: 'admin.system',
    labelEn: 'System',
    icon: Server,
    parent: '/admin',
    requiresAuth: true,
    requiredRole: 'admin',
    showInSidebar: false,
    meta: { title: 'System Health — Pyhron', description: 'System health', noIndex: true },
  },
  adminAudit: {
    path: '/admin/audit',
    label: 'admin.audit',
    labelEn: 'Audit Log',
    icon: ScrollText,
    parent: '/admin',
    requiresAuth: true,
    requiredRole: 'admin',
    showInSidebar: false,
    meta: { title: 'Audit Log — Pyhron', description: 'Full audit log', noIndex: true },
  },
};

export function getBreadcrumbs(path: string): RouteConfig[] {
  const crumbs: RouteConfig[] = [];
  let current = Object.values(ROUTES).find((r) => r.path === path);
  while (current) {
    crumbs.unshift(current);
    current = current.parent
      ? Object.values(ROUTES).find((r) => r.path === current!.parent)
      : undefined;
  }
  return crumbs;
}

// Sidebar navigation groups
export const SIDEBAR_GROUPS = [
  { id: 'main', label: 'Main' },
  { id: 'markets', label: 'Markets', parent: '/markets' },
  { id: 'research', label: 'Research', parent: '/research/dashboard' },
  { id: 'strategies', label: 'Strategies', parent: '/strategies' },
  { id: 'portfolio', label: 'Portfolio', parent: '/portfolio' },
  { id: 'advanced', label: 'Advanced' },
  { id: 'system', label: 'System' },
] as const;
