# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: equity_positions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'equity_positions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x65quity_positions.proto\x12\x17pyhron.equity_positions\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n\x08Position\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08\x65xchange\x18\x02 \x01(\t\x12\x13\n\x0bstrategy_id\x18\x03 \x01(\t\x12\x10\n\x08quantity\x18\x04 \x01(\x03\x12\x17\n\x0f\x61vg_entry_price\x18\x05 \x01(\x01\x12\x15\n\rcurrent_price\x18\x06 \x01(\x01\x12\x16\n\x0eunrealized_pnl\x18\x07 \x01(\x01\x12\x14\n\x0crealized_pnl\x18\x08 \x01(\x01\x12\x14\n\x0cmarket_value\x18\t \x01(\x01\x12\x30\n\x0clast_updated\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x82\x02\n\rPositionEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x13\n\x0bstrategy_id\x18\x03 \x01(\t\x12\x1b\n\x13triggering_order_id\x18\x04 \x01(\t\x12\x16\n\x0equantity_delta\x18\x05 \x01(\x01\x12\x17\n\x0f\x65xecution_price\x18\x06 \x01(\x01\x12\x1a\n\x12realized_pnl_delta\x18\x07 \x01(\x01\x12\x12\n\ncommission\x18\x08 \x01(\x01\x12\x0b\n\x03tax\x18\t \x01(\x01\x12/\n\x0boccurred_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x9c\x02\n\x11PortfolioSnapshot\x12\x14\n\x0cportfolio_id\x18\x01 \x01(\t\x12\x34\n\tpositions\x18\x02 \x03(\x0b\x32!.pyhron.equity_positions.Position\x12\x1a\n\x12total_market_value\x18\x03 \x01(\x01\x12\x14\n\x0c\x63\x61sh_balance\x18\x04 \x01(\x01\x12\x1c\n\x14total_unrealized_pnl\x18\x05 \x01(\x01\x12 \n\x18total_realized_pnl_today\x18\x06 \x01(\x01\x12\x18\n\x10portfolio_var_95\x18\x07 \x01(\x01\x12/\n\x0bsnapshot_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'equity_positions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSITION']._serialized_start=85
  _globals['_POSITION']._serialized_end=334
  _globals['_POSITIONEVENT']._serialized_start=337
  _globals['_POSITIONEVENT']._serialized_end=595
  _globals['_PORTFOLIOSNAPSHOT']._serialized_start=598
  _globals['_PORTFOLIOSNAPSHOT']._serialized_end=882
# @@protoc_insertion_point(module_scope)
