# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market_data_realtime.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1amarket_data_realtime.proto\x12\x1bpyhron.market_data_realtime\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x01\n\x08OHLCVBar\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08\x65xchange\x18\x02 \x01(\t\x12\x10\n\x08interval\x18\x03 \x01(\t\x12\x0c\n\x04open\x18\x04 \x01(\x01\x12\x0c\n\x04high\x18\x05 \x01(\x01\x12\x0b\n\x03low\x18\x06 \x01(\x01\x12\r\n\x05\x63lose\x18\x07 \x01(\x01\x12\x16\n\x0e\x61\x64justed_close\x18\x08 \x01(\x01\x12\x0e\n\x06volume\x18\t \x01(\x03\x12\x0c\n\x04vwap\x18\n \x01(\x01\x12,\n\x08\x62\x61r_time\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x8f\x01\n\x04Tick\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08\x65xchange\x18\x02 \x01(\t\x12\x0b\n\x03\x62id\x18\x03 \x01(\x01\x12\x0b\n\x03\x61sk\x18\x04 \x01(\x01\x12\x0c\n\x04last\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x03\x12-\n\ttick_time\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_data_realtime_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OHLCVBAR']._serialized_start=93
  _globals['_OHLCVBAR']._serialized_end=311
  _globals['_TICK']._serialized_start=314
  _globals['_TICK']._serialized_end=457
# @@protoc_insertion_point(module_scope)
