# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pre_trade_risk.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pre_trade_risk.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14pre_trade_risk.proto\x12\x15pyhron.pre_trade_risk\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x01\n\x0fRiskBreachEvent\x12\x11\n\tbreach_id\x18\x01 \x01(\t\x12\x38\n\nlimit_type\x18\x02 \x01(\x0e\x32$.pyhron.pre_trade_risk.RiskLimitType\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x13\n\x0bstrategy_id\x18\x04 \x01(\t\x12\x13\n\x0blimit_value\x18\x05 \x01(\x01\x12\x14\n\x0c\x61\x63tual_value\x18\x06 \x01(\x01\x12\x14\n\x0c\x61\x63tion_taken\x18\x07 \x01(\t\x12/\n\x0boccurred_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xbb\x01\n\x13\x43ircuitBreakerState\x12\x11\n\tis_halted\x18\x01 \x01(\x08\x12\x13\n\x0bhalt_reason\x18\x02 \x01(\t\x12\x19\n\x11halted_strategies\x18\x03 \x03(\t\x12-\n\thalted_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0e\x61uto_resume_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp*\xbe\x02\n\rRiskLimitType\x12\x1f\n\x1bRISK_LIMIT_TYPE_UNSPECIFIED\x10\x00\x12$\n RISK_LIMIT_MAX_POSITION_SIZE_PCT\x10\x01\x12\'\n#RISK_LIMIT_MAX_SECTOR_CONCENTRATION\x10\x02\x12\x1f\n\x1bRISK_LIMIT_DAILY_LOSS_LIMIT\x10\x03\x12$\n RISK_LIMIT_MAX_ORDERS_PER_MINUTE\x10\x04\x12!\n\x1dRISK_LIMIT_MAX_GROSS_EXPOSURE\x10\x05\x12\x16\n\x12RISK_LIMIT_MAX_VAR\x10\x06\x12\x1b\n\x17RISK_LIMIT_MIN_LOT_SIZE\x10\x07\x12\x1e\n\x1aRISK_LIMIT_T2_BUYING_POWER\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pre_trade_risk_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RISKLIMITTYPE']._serialized_start=519
  _globals['_RISKLIMITTYPE']._serialized_end=837
  _globals['_RISKBREACHEVENT']._serialized_start=81
  _globals['_RISKBREACHEVENT']._serialized_end=326
  _globals['_CIRCUITBREAKERSTATE']._serialized_start=329
  _globals['_CIRCUITBREAKERSTATE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
