# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strategy_signals.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16strategy_signals.proto\x12\x17pyhron.strategy_signals\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x03\n\x06Signal\x12\x11\n\tsignal_id\x18\x01 \x01(\t\x12\x13\n\x0bstrategy_id\x18\x02 \x01(\t\x12\x0e\n\x06symbol\x18\x03 \x01(\t\x12\x10\n\x08\x65xchange\x18\x04 \x01(\t\x12;\n\tdirection\x18\x05 \x01(\x0e\x32(.pyhron.strategy_signals.SignalDirection\x12\x15\n\rtarget_weight\x18\x06 \x01(\x01\x12\x12\n\nconfidence\x18\x07 \x01(\x01\x12\x13\n\x0bsignal_type\x18\x08 \x01(\t\x12H\n\rfactor_values\x18\t \x03(\x0b\x32\x31.pyhron.strategy_signals.Signal.FactorValuesEntry\x12\x30\n\x0cgenerated_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0bvalid_until\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a\x33\n\x11\x46\x61\x63torValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01*\xa6\x01\n\x0fSignalDirection\x12 \n\x1cSIGNAL_DIRECTION_UNSPECIFIED\x10\x00\x12\x19\n\x15SIGNAL_DIRECTION_LONG\x10\x01\x12\x1a\n\x16SIGNAL_DIRECTION_SHORT\x10\x02\x12\x1a\n\x16SIGNAL_DIRECTION_CLOSE\x10\x03\x12\x1e\n\x1aSIGNAL_DIRECTION_REBALANCE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'strategy_signals_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SIGNAL_FACTORVALUESENTRY']._options = None
  _globals['_SIGNAL_FACTORVALUESENTRY']._serialized_options = b'8\001'
  _globals['_SIGNALDIRECTION']._serialized_start=521
  _globals['_SIGNALDIRECTION']._serialized_end=687
  _globals['_SIGNAL']._serialized_start=85
  _globals['_SIGNAL']._serialized_end=518
  _globals['_SIGNAL_FACTORVALUESENTRY']._serialized_start=467
  _globals['_SIGNAL_FACTORVALUESENTRY']._serialized_end=518
# @@protoc_insertion_point(module_scope)
