"""Order event schemas for the Enthropy trading platform.

Defines Pydantic v2 models for the full order lifecycle: request
submission, fills, cancellations, and status updates.  All models
enforce multi-tenancy via mandatory ``tenant_id`` fields.
"""

from __future__ import annotations

from datetime import UTC, datetime
from decimal import Decimal
from enum import IntEnum, StrEnum
from typing import Optional
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, model_validator

# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class OrderSide(StrEnum):
    """Order direction."""

    BUY = "BUY"
    SELL = "SELL"


class OrderType(StrEnum):
    """Supported order types."""

    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"
    MOC = "MOC"  # Market On Close
    LOC = "LOC"  # Limit On Close
    TWAP = "TWAP"
    VWAP = "VWAP"
    ICEBERG = "ICEBERG"


class OrderStatusEnum(StrEnum):
    """Lifecycle states of an order."""

    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class TimeInForce(StrEnum):
    """Time-in-force instructions."""

    DAY = "DAY"
    GTC = "GTC"  # Good Till Cancelled
    IOC = "IOC"  # Immediate Or Cancel
    FOK = "FOK"  # Fill Or Kill
    GTD = "GTD"  # Good Till Date
    OPG = "OPG"  # At the Open


class CancelReason(StrEnum):
    """Reason an order was cancelled."""

    USER_REQUESTED = "USER_REQUESTED"
    RISK_LIMIT = "RISK_LIMIT"
    TIMEOUT = "TIMEOUT"
    EXCHANGE_REJECTED = "EXCHANGE_REJECTED"
    SYSTEM = "SYSTEM"


# ---------------------------------------------------------------------------
# Models
# ---------------------------------------------------------------------------

class OrderEventBase(BaseModel):
    """Base fields shared across all order events."""

    model_config = {"frozen": True, "str_strip_whitespace": True}

    order_id: UUID = Field(default_factory=uuid4, description="Unique order identifier")
    symbol: str = Field(..., min_length=1, max_length=20, description="Instrument symbol")
    side: OrderSide = Field(..., description="BUY or SELL")
    qty: Decimal = Field(..., gt=0, description="Order quantity")
    price: Decimal | None = Field(default=None, ge=0, description="Limit / stop price (None for market orders)")
    order_type: OrderType = Field(default=OrderType.LIMIT, description="Order type")
    tenant_id: str = Field(..., min_length=1, max_length=64, description="Tenant identifier")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(tz=UTC), description="Event timestamp (UTC)")


class OrderRequest(OrderEventBase):
    """New order submission request.

    Sent by a trading strategy or the order-entry UI to the OMS.
    Contains all information needed to route the order to the market.
    """

    time_in_force: TimeInForce = Field(default=TimeInForce.DAY, description="Time-in-force instruction")
    account_id: str | None = Field(default=None, max_length=64, description="Trading account / sub-account")
    strategy_id: str | None = Field(default=None, max_length=64, description="Originating strategy identifier")
    stop_price: Decimal | None = Field(default=None, ge=0, description="Stop trigger price (for STOP / STOP_LIMIT)")
    display_qty: Decimal | None = Field(default=None, ge=0, description="Display quantity for iceberg orders")
    client_order_id: str | None = Field(default=None, max_length=64, description="Client-assigned order reference")

    @model_validator(mode="after")
    def _validate_price_for_type(self) -> OrderRequest:
        if self.order_type == OrderType.LIMIT and self.price is None:
            raise ValueError("Limit orders require a price")
        if self.order_type in (OrderType.STOP, OrderType.STOP_LIMIT) and self.stop_price is None:
            raise ValueError(f"{self.order_type} orders require a stop_price")
        if self.order_type == OrderType.ICEBERG and (self.display_qty is None or self.display_qty <= 0):
            raise ValueError("Iceberg orders require a positive display_qty")
        return self


class OrderFill(OrderEventBase):
    """Execution / fill report.

    Generated by the OMS when a partial or complete fill is received
    from the exchange.
    """

    fill_id: UUID = Field(default_factory=uuid4, description="Unique fill identifier")
    fill_qty: Decimal = Field(..., gt=0, description="Filled quantity in this execution")
    fill_price: Decimal = Field(..., gt=0, description="Execution price")
    cumulative_qty: Decimal = Field(..., ge=0, description="Total filled quantity so far")
    leaves_qty: Decimal = Field(..., ge=0, description="Remaining open quantity")
    status: OrderStatusEnum = Field(default=OrderStatusEnum.PARTIALLY_FILLED, description="Order status after fill")
    commission: Decimal = Field(default=Decimal("0"), ge=0, description="Commission charged for this fill")
    exchange: str | None = Field(default=None, max_length=20, description="Execution venue")
    liquidity_flag: str | None = Field(
        default=None,
        pattern=r"^(ADD|REMOVE|ROUTED)$",
        description="Liquidity indicator",
    )

    @model_validator(mode="after")
    def _validate_fill_quantities(self) -> OrderFill:
        if self.cumulative_qty + self.leaves_qty != self.qty:
            raise ValueError("cumulative_qty + leaves_qty must equal qty")
        if self.leaves_qty == 0 and self.status != OrderStatusEnum.FILLED:
            raise ValueError("Status must be FILLED when leaves_qty is 0")
        return self


class OrderCancel(OrderEventBase):
    """Order cancellation event.

    Emitted when an order is cancelled either by user request, risk
    controls, or exchange rejection.
    """

    cancel_reason: CancelReason = Field(default=CancelReason.USER_REQUESTED, description="Reason for cancellation")
    status: OrderStatusEnum = Field(default=OrderStatusEnum.CANCELLED, description="Order status (always CANCELLED)")
    cancelled_qty: Decimal = Field(..., ge=0, description="Quantity that was cancelled")
    filled_qty: Decimal = Field(default=Decimal("0"), ge=0, description="Quantity already filled before cancel")
    detail: str | None = Field(default=None, max_length=512, description="Human-readable cancellation detail")


class OrderStatus(OrderEventBase):
    """Point-in-time order status snapshot.

    Provides a full view of the current state of an order including
    fill progress and average execution price.
    """

    status: OrderStatusEnum = Field(..., description="Current order status")
    filled_qty: Decimal = Field(default=Decimal("0"), ge=0, description="Total filled quantity")
    remaining_qty: Decimal = Field(..., ge=0, description="Remaining open quantity")
    avg_fill_price: Decimal | None = Field(default=None, ge=0, description="Volume-weighted average fill price")
    commission_total: Decimal = Field(default=Decimal("0"), ge=0, description="Total commissions paid")
    last_updated: datetime = Field(default_factory=lambda: datetime.now(tz=UTC), description="Last status change time")


# ---------------------------------------------------------------------------
# Kafka Event Schemas (OMS domain events)
# ---------------------------------------------------------------------------


class OrderSubmittedEvent(BaseModel):
    """Published when an order is submitted to a broker."""

    model_config = {"frozen": True}

    event_id: str = Field(default_factory=lambda: str(uuid4()))
    event_type: str = "ORDER_SUBMITTED"
    timestamp: str = Field(description="ISO8601 UTC")
    order_id: str
    client_order_id: str
    user_id: str
    strategy_id: str | None = None
    symbol: str
    exchange: str = "IDX"
    side: str
    order_type: str
    quantity_lots: int
    limit_price: str | None = None
    submitted_at: str = ""


class OrderFilledEvent(BaseModel):
    """Published when an order fill is processed."""

    model_config = {"frozen": True}

    event_id: str = Field(default_factory=lambda: str(uuid4()))
    event_type: str = "ORDER_FILLED"
    timestamp: str = Field(description="ISO8601 UTC")
    order_id: str
    symbol: str
    side: str
    fill_price: str
    fill_quantity_lots: int
    total_filled_lots: int
    avg_fill_price: str
    commission_idr: str
    settlement_date: str
    is_full_fill: bool


class PositionUpdatedEvent(BaseModel):
    """Published when a position is updated after a fill."""

    model_config = {"frozen": True}

    event_id: str = Field(default_factory=lambda: str(uuid4()))
    event_type: str = "POSITION_UPDATED"
    timestamp: str = Field(description="ISO8601 UTC")
    user_id: str
    strategy_id: str | None = None
    symbol: str
    quantity_lots: int
    avg_cost_idr: str
    unrealized_pnl_idr: str
    realized_pnl_idr: str
    last_fill_price: str


__all__ = [
    "CancelReason",
    "OrderCancel",
    "OrderEventBase",
    "OrderFill",
    "OrderFilledEvent",
    "OrderRequest",
    "OrderSide",
    "OrderStatus",
    "OrderStatusEnum",
    "OrderSubmittedEvent",
    "OrderType",
    "PositionUpdatedEvent",
    "TimeInForce",
]
