"""Sample order lifecycle events for testing.

Provides a complete order lifecycle from NEW -> SUBMITTED -> PARTIAL_FILL -> FILLED,
plus examples of rejected and cancelled orders.
"""

from __future__ import annotations

from datetime import UTC, datetime

ORDER_LIFECYCLE_HAPPY_PATH = [
    {
        "event_id": "evt-001",
        "client_order_id": "ord-2025-001",
        "symbol": "BBCA",
        "side": "buy",
        "quantity": 1000,
        "limit_price": 9200.0,
        "from_status": "pending_risk",
        "to_status": "risk_approved",
        "source": "risk_engine",
        "occurred_at": datetime(2025, 1, 6, 2, 30, 0, tzinfo=UTC),
        "filled_quantity": 0,
        "filled_price": 0.0,
        "commission": 0.0,
        "tax": 0.0,
    },
    {
        "event_id": "evt-002",
        "client_order_id": "ord-2025-001",
        "symbol": "BBCA",
        "side": "buy",
        "quantity": 1000,
        "limit_price": 9200.0,
        "from_status": "risk_approved",
        "to_status": "submitted",
        "source": "oms",
        "occurred_at": datetime(2025, 1, 6, 2, 30, 1, tzinfo=UTC),
        "filled_quantity": 0,
        "filled_price": 0.0,
        "commission": 0.0,
        "tax": 0.0,
    },
    {
        "event_id": "evt-003",
        "client_order_id": "ord-2025-001",
        "symbol": "BBCA",
        "side": "buy",
        "quantity": 1000,
        "limit_price": 9200.0,
        "from_status": "submitted",
        "to_status": "acknowledged",
        "source": "broker_ws",
        "occurred_at": datetime(2025, 1, 6, 2, 30, 2, tzinfo=UTC),
        "filled_quantity": 0,
        "filled_price": 0.0,
        "commission": 0.0,
        "tax": 0.0,
    },
    {
        "event_id": "evt-004",
        "client_order_id": "ord-2025-001",
        "symbol": "BBCA",
        "side": "buy",
        "quantity": 1000,
        "limit_price": 9200.0,
        "from_status": "acknowledged",
        "to_status": "partial_fill",
        "source": "broker_ws",
        "occurred_at": datetime(2025, 1, 6, 2, 31, 0, tzinfo=UTC),
        "filled_quantity": 500,
        "filled_price": 9175.0,
        "commission": 6881.25,
        "tax": 0.0,
    },
    {
        "event_id": "evt-005",
        "client_order_id": "ord-2025-001",
        "symbol": "BBCA",
        "side": "buy",
        "quantity": 1000,
        "limit_price": 9200.0,
        "from_status": "partial_fill",
        "to_status": "filled",
        "source": "broker_ws",
        "occurred_at": datetime(2025, 1, 6, 2, 32, 0, tzinfo=UTC),
        "filled_quantity": 1000,
        "filled_price": 9185.0,
        "commission": 13_777.50,
        "tax": 0.0,
    },
]

ORDER_RISK_REJECTED = {
    "event_id": "evt-010",
    "client_order_id": "ord-2025-002",
    "symbol": "BBRI",
    "side": "buy",
    "quantity": 100_000,
    "limit_price": 5500.0,
    "from_status": "pending_risk",
    "to_status": "risk_rejected",
    "source": "risk_engine",
    "occurred_at": datetime(2025, 1, 6, 3, 0, 0, tzinfo=UTC),
    "rejection_reason": "Position would be 55.0% of portfolio (limit: 10.0%)",
    "filled_quantity": 0,
    "filled_price": 0.0,
}

ORDER_CANCELLED = {
    "event_id": "evt-020",
    "client_order_id": "ord-2025-003",
    "symbol": "TLKM",
    "side": "sell",
    "quantity": 500,
    "limit_price": 3900.0,
    "from_status": "acknowledged",
    "to_status": "cancelled",
    "source": "user_request",
    "occurred_at": datetime(2025, 1, 6, 4, 0, 0, tzinfo=UTC),
    "filled_quantity": 0,
    "filled_price": 0.0,
}
